export const PointLockEventEnum = 
{
	LOCK: "LOCK",
	UNLOCK: "UNLOCK",
    MOUSEMOVE: "MOUSEMOVE",
};

export const UserInputEventEnum = 
{

    BUTTON_SWITCH_PRIMARY_WEAPON: "BUTTON_SWITCH_PRIMARY_WEAPON",
    BUTTON_SWITCH_SECONDARY_WEAPON: "BUTTON_SWITCH_SECONDARY_WEAPON",
    BUTTON_SWITCH_SNIPER_WEAPON: "BUTTON_SWITCH_SNIPER_WEAPON",
    BUTTON_SWITCH_MELEE_WEAPON: "BUTTON_SWITCH_MELEE_WEAPON",
    BUTTON__SWITCH_LAST_WEAPON: "BUTTON__SWITCH_LAST_WEAPON",

    BUTTON_ADS_UP: "BUTTON_ADS_UP",
    BUTTON_ADS_DOWN: "BUTTON_ADS_DOWN",

    BUTTON_RELOAD: "BUTTON_RELOAD",
    BUTTON_TRIGGLE_DOWN: "BUTTON_TRIGGLE_DOWN",
    BUTTON_TRIGGLE_UP: "BUTTON_TRIGGLE_UP",
    BUTTON_SHIFT_DOWN: "BUTTON_SHIFT_DOWN",
    BUTTON_SHIFT_UP: "BUTTON_SHIFT_UP",
    MOVE_FORWARD_DOWN: "MOVE_FORWARD_DOWN",
    MOVE_BACKWARD_DOWN: "MOVE_BACKWARD_DOWN",
    MOVE_LEFT_DOWN: "MOVE_LEFT_DOWN",
    MOVE_RIGHT_DOWN: "MOVE_RIGHT_DOWN",
    MOVE_FORWARD_UP: "MOVE_FORWARD_UP",
    MOVE_BACKWARD_UP: "MOVE_BACKWARD_UP",
    MOVE_LEFT_UP: "MOVE_LEFT_UP",
    MOVE_RIGHT_UP: "MOVE_RIGHT_UP",
    JUMP: "JUMP",
};

export const WeaponAnimationEventEnum =
{
    DRAW: "DRAW",
    REMOVE: "REMOVE",
    ADS: "ADS",
    ADS_FIRE: "ADS_FIRE",
    FIRE: "FIRE",
    RELOAD: "RELOAD",
    IDLE: "IDLE",
    WALK: "WALK",
    RUN: "RUN",
    JUMP: "JUMP",
};

export const GameEventEnum = 
{
    RESIZING: "RESIZING",
    LAUNCH: 'launch',
	READY: 'ready',
}

export const NetworkEventEnum = 
{
    CONNECT: 'connect',
    DISCONNECT: 'disconnect',
    JOIN: 'join',
    LEAVE: 'leave',
    MESSAGE: 'message',
    ERROR: 'error',
    SET_NAME: 'set_name',
}