export const PointLockEventEnum = 
{
	LOCK: "LOCK",
	UNLOCK: "UNLOCK",
    MOUSEMOVE: "MOUSEMOVE",
};

export const UserInputEventEnum = 
{

    BUTTON_SWITCH_PRIMARY_WEAPON: "BUTTON_SWITCH_PRIMARY_WEAPON",
    BUTTON_SWITCH_SECONDARY_WEAPON: "BUTTON_SWITCH_SECONDARY_WEAPON",
    BUTTON_SWITCH_MELEE_WEAPON: "BUTTON_SWITCH_MELEE_WEAPON",
    BUTTON_SWITCH_LAST_WEAPON: "BUTTON_SWITCH_LAST_WEAPON",

    BUTTON_RELOAD: "BUTTON_RELOAD",
    BUTTON_TRIGGLE_DOWN: "BUTTON_TRIGGLE_DOWN",
    BUTTON_TRIGGLE_UP: "BUTTON_TRIGGLE_UP",
    BUTTON_SHIFT_DOWN: "BUTTON_SHIFT_DOWN",
    BUTTON_SHIFT_UP: "BUTTON_SHIFT_UP",
    MOVE_FORWARD_DOWN: "MOVE_FORWARD_DOWN",
    MOVE_BACKWARD_DOWN: "MOVE_BACKWARD_DOWN",
    MOVE_LEFT_DOWN: "MOVE_LEFT_DOWN",
    MOVE_RIGHT_DOWN: "MOVE_RIGHT_DOWN",
    MOVE_FORWARD_UP: "MOVE_FORWARD_UP",
    MOVE_BACKWARD_UP: "MOVE_BACKWARD_UP",
    MOVE_LEFT_UP: "MOVE_LEFT_UP",
    MOVE_RIGHT_UP: "MOVE_RIGHT_UP",
    JUMP: "JUMP",
};

export const WeaponAnimationEventEnum =
{
    HOLD: "HOLD",
    EQUIP: "EQUIP",
    RELIEVE_EQUIP: "RELIEVE_EQUIP",
    FIRE: "FIRE",
    RELOAD: "RELOAD",
    PICKUP: "PICKUP"
};